### ISSUE TITLE
Web Clipper ignores Windows screen scaling

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1202]
Just tried "Clip Screenshot" for the first time. It pretty obviously ignores screen scaling. In this full screen image, I clipped the blue rectangle:
![2020-08-23](https://user-images.githubusercontent.com/1297090/91008288-e6e56280-e592-11ea-8c8f-2173af470c86.png)

And it saved an area about half that size, about halfway toward the top left corner:
![Trilium scaling](https://user-images.githubusercontent.com/1297090/91008353-0f6d5c80-e593-11ea-9e99-b818a686346d.JPG)

Anything I can do to fix that? Short of turning off scaling...

**Comment by zadam** [comment]
Hi, you're probably right, clipper probably ignores scaling. I develop/test on "normal" DPI displays so it never occurred to me. I'll see how I can reproduce and fix this.

**Comment by LorenAmelang** [comment]
I'm happy to test fixes if you like. I have way too much experience fighting scaling...

**Comment by Maatteogekko** [comment]
Hi, is there any progress to fix this issue? I can also help testing if needed.

**Comment by zadam** [comment]
Hi all, today I tested the web clipper on a HiDPI display with scaling enabled and screenshot was clipped correctly. 

So just to be sure, are you using the latest 0.2 version of web clipper?

**Comment by LorenAmelang** [comment]
My Clipper says 0.2.0

Just tried a new outline clip, and also the exact one I reported before - both worked, got the correct outline! I have not intentionally changed my screen scaling, but Microsoft changes things daily...  My Vivaldi browser changes frequently, too. 

I think maybe the Clipper interacts with my Dark Reader extension...  First try the whole page went half dim, and the selected outline went full bright. Second try, the page went half dim and the outline went even darker, and didn't clip. I tried a new outline on the same dim page, and it went almost black - and clipped the dim image. Third try the outline went bright and clipped the proper bright image again. Probably not worth digging into, dark modes are voodoo...  

The "background page" shows:

DevTools failed to load SourceMap: Could not load content for chrome-extension://dfhgmnfclbebfobmblelddiejjcijbjm/lib/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

(I get those on most every page I look at, from some extension or another.)

And (I suppose because my Trilium isn't running at the moment) thousands of these:

 Failed to load resource: net::ERR_CONNECTION_REFUSED  http://127.0.0.1:37841/api/clipper/handshake

GET http://127.0.0.1:37849/api/clipper/handshake net::ERR_CONNECTION_REFUSED
triggerSearchForTrilium @ trilium_server_facade.js:62
async function (async)
triggerSearchForTrilium @ trilium_server_facade.js:56
(anonymous) @ trilium_server_facade.js:14

They stop once Trilium is running.

**Comment by Maatteogekko** [comment]
Thanks for looking into this issue again, I am using the latest version of the plugins.
I reinstalled the plugin on firefox and chrome and then tried to take a screenshot with the web clipper. The subject is the first image of the README of your Trilium repository. These are the results:
- chrome
![image](https://user-images.githubusercontent.com/54111322/113939997-0cab3900-97fd-11eb-911f-362c72a9b1a2.png)  
- irefox
![image](https://user-images.githubusercontent.com/54111322/113940101-39f7e700-97fd-11eb-8dd5-cc56021aa7f7.png)

I tried with and without the darkreader extension enabled, but there was no difference in the results. Both tests were made without Trilium's desktop instance open.
Chrome's one is perfect, so the problem is with firefox's version of the plugin?

PS: I'm on Linux

**Comment by LorenAmelang** [comment]
Maatteogekko is right - Firefox still shows the classic scaling problem, clips a smaller portion of the screen, from partway to the top left corner, and shows it bigger than it should be. (I just installed the extension from GitHub in Firefox 87.0 (64-bit) on Win 10.) 

My Vivaldi (Chromium) used to do that, but now clips correctly.

**Comment by zadam** [comment]
Thanks for info. Firefox and Chrome plugins are identical, just packaged differently. But there might be some difference in webextension API between them. I'll check it out.

**Comment by zadam** [comment]
Hi, the bug has been fixed in firefox and released in the new 0.3.0 version: https://github.com/zadam/trilium-web-clipper/releases/tag/v0.3.0

**Comment by LorenAmelang** [comment]
Sorry for my ignorance, but how to install it? Vivaldi extension tab "Update" button finds nothing, probably because 
https://chrome.google.com/webstore/detail/trilium-web-clipper/dfhgmnfclbebfobmblelddiejjcijbjm?hl=en-US
still shows 0.2.0 version. I downloaded the 
https://github.com/zadam/trilium-web-clipper/releases/download/v0.3.0/trilium_web_clipper-0.3.0-chrome.zip
folder, but it is just the .js and details, no installer. I'd copy them over the old ones, but I can't find the current location! Not with the Trilium code, not with Vivaldi or its AppData...  Where is it hiding? 

Checked Firefox, explicitly asked for updates - it found others, but Clipper is still 0.2.0 version. The new .xpi file isn't recognized in Windows either.

**Comment by zadam** [comment]
\[https://chrome.google.com/webstore/detail/trilium-web-clipper/dfhgmnfclbebfobmblelddiejjcijbjm?hl=en-US](chrome web store) already has 0.3.0. I think the new version just took some time to pass the review process.

For Firefox there's currently only manual installation only since I did not figure out how to publish on FF store :-( So you need to download from [https://github.com/zadam/trilium-web-clipper/releases/tag/v0.3.0](https://github.com/zadam/trilium-web-clipper/releases/tag/v0.3.0) and install:

![](https://user-images.githubusercontent.com/617641/114317270-88f89180-9b07-11eb-985a-0f51bb34df79.png)

**Comment by LorenAmelang** [comment]
Yes, Vivaldi automatically found 0.3.0 today. Firefox did not, but that "Install Add-on From File" choice worked with the .xpi file I downloaded yesterday. 

Firefox clips the proper page segment now. 

Thanks!
