### ISSUE TITLE
Webclipping has broken Trilium

### ISSUE THREAD

**Issue by Waxwood** [zadam/trilium#1532]
Installed: v0.45.7 
Operating system: Manjaro linux
Log: attached

I clipped a URL in Firefox, but when I clicked View in Trilium, the program displayed an number of images and froze. Now, each time I attempt to start Trilium, the image appears but Trilium will not function. 
I have been starting Trilium using this command in terminal: TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data trilium

What is causing this? Thank you for your work on Trilium.

[trilium-2021-01-11.log](https://github.com/zadam/trilium/files/5798053/trilium-2021-01-11.log)
![Trilium- webclipping from specific URL messed up Trilium](https://user-images.githubusercontent.com/26566207/104231787-121f0000-5415-11eb-9a9e-e6a9326c62ee.png)

**Comment by zadam** [comment]
Hello, thank you for reporting this problem.

The clipped page is probably "hijacking" the whole document with javascript which is typical of some older web page programming style. I need to investigate why is this happening because the clipped pages should be cleaned up of any JavaScripts etc.

However, now your immediate problem is that you're blocked from using Trilium because on startup it always attempts to load this "hijacked" note. I just released 0.45.8 so please download that and now run:

```
TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data trilium
```

**Comment by Waxwood** [comment]
Hello Zadam, 
Your fast reply is much appreciated! 
I followed your instructions and Trilium is running once again. 
I had to delete the old directory because for some reason, Dolphin would not copy over it without crashing.

I'm glad my report can be of some use in improving Trilium. Thank you again.

**Comment by Waxwood** [comment]
Hi, The problem has returned. 
While searching through my notes, I clicked on the screenclipped note that caused the "hijacking" and the problem returned. Now I can't use Trilum again. 
Once I can access Trilium again, I'll find the URL causing this problem and send it to you for testing.

I hope there's a fairly easy fix for this.

**Comment by zadam** [comment]
Hi, yes, the guide I posted was only a workaround for the issue. Use that command again to get back to useable trilium but you can't activate that note again. The best way to proceed for you would be to locate the note in the tree (without left clicking on it), then right click and delete the note from context menu.

**Comment by Waxwood** [comment]
I used that command again, but it did not resolve the problem. 
I'll definitely delete that "contagion" note as soon as I can. 

I have attached the log file to help with figuring out this problem
[trilium-2021-01-14.log](https://github.com/zadam/trilium/files/5818064/trilium-2021-01-14.log)

**Comment by zadam** [comment]
Hi, log says it's version 0.45.4, as mentioned in the comment you need 0.45.8 for the workaround comment to work ...

**Comment by Waxwood** [comment]
Hi, Thank you. That is very weird indeed. As far as I know, I deleted the previous folder and installed 0.45.8 as you recommended last time.  I must have done something wrong. 
I'll unzip 0.45.8 into the folder and overwrite the previous files again.

**Comment by Waxwood** [comment]
I downloaded this file trilium-windows-x64-0.45.8.zip then unzipped it into folder "trilium-linux-x64" after after renaming the the original Trilium folder as "OLD-trilium-linux-x64"
However, the problem persists.
I checked the log which indicates that the version is 
  "appVersion": "0.45.4",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2020-11-12T22:15:23+01:00",
  "buildRevision": "6c57b2220ff05059d7460369b195d281fcd9cbb6",
  "dataDirectory": "/home/ray1/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"

This leads me to wonder if, perhaps, you accidentally packaged the old version inadvertently thinking it was the new version 0.45.8.
Is there something else causing this?
My Trilium data folder is here: /home/ray1/trilium-data
The Trilium program files are here: /home/ray1/trilium/trilium-linux-x64

Thank you!

**Comment by zDEFz** [comment]
@zadam can you forbid certain instructions from note entirely?
https://www.w3schools.com/jsref/met_doc_write.asp

Document.Write() would be another candidate emptying the entire screen.

Also, I'm sorry about the recent "clash" and have updated the instructions for Docker in the Wiki, so noobs like me can understand it :)

**Comment by zadam** [comment]
@Waxwood I checked and the package contains the correct version. I think somehow you must be executing the old version.

One thing which seems odd is that you're describing "trilium-windows-x64-0.45.8.zip" although you're running on linux.

You can perhaps use `which trilium` to check what executable is being run, alternatively execute trilium using an absolute path.

> Document.Write() would be another candidate emptying the entire screen.

Yes, this often causes this hijacking. Unfortunately I don't know how this could be disabled. Web/JavaScript was not designed for such embedding / sandboxing. My strategy is to simply strip out all JavaScript when importing/clipping pages.

> Also, I'm sorry about the recent "clash" and have updated the instructions for Docker in the Wiki, so noobs like me can understand it :)

No harm done ...

**Comment by Waxwood** [comment]
This is an odd case indeed.
The reference to the windows package was a mistake- I copied the wrong filename. I've corrected this error in my previous post. 

I ran the command "which Trilium" which, to my surprise, returned "/usr/bin/trilium".
It seems that I did not properly uninstall the version of Trilium from Manjaro AUR. 
I have uninstalled it and rebooted.

But now when I run "TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data trilium" I receive this "bash: trilium: command not found".

How should I proceed? Thanks!

**Comment by mbafford** [comment]
@Waxwood It sounds like bash has cached the path and is still looking for trilium at /usr/bin/trilium or the path you installed trilium to isn't in bash's PATH. 

Does it run if you use an explicit path to the version you just installed?

e.g.:
```TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data /path/to/installed/trilium```

**Comment by Waxwood** [comment]
@mbafford I didn't realize that bash can cache a path like that. 

I tried running it using the explicit path:
`TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data /home/ray1/trilium/trilium-linux-x64/trilium`
But it failed with this message: 
```
[12927:0115/145125.990715:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
```

**Comment by mbafford** [comment]
> @mbafford I didn't realize that bash can cache a path like that.

@Waxwood [Yes, bash will cache](https://unix.stackexchange.com/a/5610/168467), although your reboot and the fact the path you specified (`~/trilium/trilium-linux-x64/`) is so nested in your home folder makes me think it's more likely this path is just not in your PATH environment variable.

> `Running as root without --no-sandbox is not supported.`
It looks like you're running trilium as the root user, not your personal user account. The command `whoami` will help clear up what user you're running the command under. It's generally not advisable to run anything as root unless you have a specific reason to do so.

This error is coming from the electron wrapper Trilium uses (which allows Trilium to serve the webpages that drive the UI, as if they were a native app), it's not specifically a Trilium error.

**Comment by Waxwood** [comment]
@mbafford Thank you very much for your reply!
I can move the Trilium folder up one level in the path if this might help resolve problems.

I don't particularly understand the command 
TRILIUM_START_NOTE_ID=root TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data /home/ray1/trilium/trilium-linux-x64/trilium

Which was provided to me earlier in these posts. Does "TRILIUM_START_NOTE_ID=root" tell the system to start as root?
How can I start Trilium without this command? Double clicking on the executable does not start the program.

I have other apps that are running on Electron (Hamsket and others) without problems. 
How might I resolve the problem I'm having?
Thank you

**Comment by zadam** [comment]
> Which was provided to me earlier in these posts. Does "TRILIUM\_START\_NOTE\_ID=root" tell the system to start as root?

No, that's just coincidence in terminology. It tells that Trilium should display root note, but has nothing to do with linux root user.

I don't know why the app is starting under a root user, that is strange (but most probably not a trilium's issue).

**Comment by mbafford** [comment]
Confusing double-use of root here.

This part of the command:
```TRILIUM_START_NOTE_ID=root```

sets an environment variable passed to Trilium asking it to display a single note, with the ID `root`. This is unrelated to what I was talking about regarding the error message from Electron.

The other part of that command sets another environment variable that tells Trilium where to search for the data files:
```TRILIUM_DATA_DIR=/home/ray1/.local/share/trilium-data```

The `root` I was referring to is the superuser/root user in Linux. Normally in Linux you'd execute commands as your own user account (looks like it might be named `ray1`). I'm not familiar with Manjaro Linux, but I'd be surprised if it uses `root` to run commands. (Here's Manjaro's [entry on this](https://wiki.manjaro.org/index.php/Linux_Security)).

Are you opening a terminal window to run these commands? Make sure you're not opening an "administrator" or "root" terminal, and that ```whoami``` doesn't output "root".

**Comment by Waxwood** [comment]
Thank you for your patience @mbafford. Your explanations are easy to understand.  Much appreciated.
You are right, Manjaro does not normally start terminal as root. 
I earlier inadvertently running as root when I installed something in a terminal windows. I neglected to shut down that terminal window when trying the Trilium command to start it pointing at the drirectory in Home. 

I opened a new terminal window, checked whois and confirmed it is ray1. After that I ran the command and Trilium started. I checked and it is 0.45.8

Thank you and @zadam for helping me resolve this.

**Comment by Waxwood** [comment]
The crash originally occurred after capturing this article (https://www.vox.com/identities/2017/9/1/15951874/prosperity-gospel-explained-why-joel-osteen-believes-prayer-can-make-you-rich-trump) for a sociological research project.
No wonder it zombified and took over my Trilium installation.
