### ISSUE TITLE
(Bug report)  Parsing error: The keyword ‘count’ is reserved

### ISSUE THREAD

**Issue by Daniel-RUS** [zadam/trilium#4911]
### Trilium Version

v0.91.6

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

W 11

### Description

Hello. 
I can't figure out what's wrong. I am moving trilium to a computer without internet in a zip file. After opening it I want to use the task manager. It doesn't work. I.e. I create a new task TODO and it does not appear in the tags. Moreover, if I open any script, there is an error: “Parsing error: The keyword ‘count’ is reserved”. In general, no external scripts from extensions or internal scripts work. This is also observed in the stable version. 

Translated with DeepL.com (free version)

### Error logs

09:14:53.810 Slow query took 43ms: SELECT value FROM options WHERE name = 'initialized'
09:14:54.414 DB size: 5017 KB
09:14:54.828 Becca (note cache) load took 406ms
09:14:54.880 Slow query took 23ms: INSERT INTO branches (branchId, noteId, parentNoteId, prefix, notePosition, isExpanded, isDeleted, utcDateModified) VALUES (@branchId, @noteId, @parentNoteId, @prefix, @notePosition, @isExpanded, @isDeleted, @utcDateModified) ON CONFLICT (branchId) DO UPDATE SET branchId = @branchId, noteId = @noteId, parentNoteId = @parentNoteId, prefix = @prefix, notePosition = @notePosition, isExpanded = @isExpanded, isDeleted = @isDeleted, utcDateModified = @utcDateModified
09:14:54.910 Slow query took 29ms: INSERT OR REPLACE INTO entity_changes ( entityName, entityId, hash, isErased, utcDateChanged, isSynced, changeId, componentId, instanceId ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
09:14:54.945 {
  "appVersion": "0.91.6",
  "dbVersion": 228,
  "nodeVersion": "v20.18.1",
  "syncVersion": 34,
  "buildDate": "2025-02-03T17:08:57Z",
  "buildRevision": "79e830b6ea22e51196bdca4c021f30ecfad92723",
  "dataDirectory": "Z:\\123\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2025-03-07T06:14:51.801Z"
}
09:14:54.946 CPU model: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, logical cores: 8, freq: 4008 Mhz
09:14:54.946 Trusted reverse proxy: false
09:14:54.946 App HTTP server starting up at port 37840
09:14:54.949 Listening on port 37840
09:14:55.227 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
09:14:55.966 CSRF token generation: Successful
09:14:56.835 200 GET /api/options with 8463 bytes took 1ms
09:14:56.839 200 GET /api/keyboard-actions with 14449 bytes took 3ms
09:14:56.841 200 GET /api/tree with 74300 bytes took 2ms
09:14:56.932 Slow query took 79ms: SELECT content FROM blobs WHERE blobId = ?
09:14:57.076 200 GET /api/script/widgets with 2 bytes took 1ms
09:14:57.199 200 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 0ms
09:14:57.204 200 POST /api/tree/load with 5211 bytes took 1ms
09:14:57.205 200 GET /api/tree?subTreeNoteId=7E2MquCh56bK with 8033 bytes took 0ms
09:14:57.206 200 GET /api/tree?subTreeNoteId=_lbMobileAvailableLaunchers with 4380 bytes took 0ms
09:14:57.691 Slow query took 68ms: SELECT *, LENGTH(content) AS contentLength FROM blobs WHERE blobId = ?
09:14:57.691 Slow 200 GET /api/notes/Hl8cw7PNHA5w/blob with 12184 bytes took 69ms
09:14:57.693 200 GET /api/tree?subTreeNoteId=q1IwHJJZKM3u with 3324 bytes took 1ms
09:14:57.708 200 GET /api/tree?subTreeNoteId=vSnZflsw7BVD with 8012 bytes took 1ms
09:14:57.719 204 PUT /api/branches/root_q1IwHJJZKM3u/expanded/1 with 0 bytes took 7ms
09:14:57.720 204 PUT /api/branches/q1IwHJJZKM3u_vSnZflsw7BVD/expanded/1 with 0 bytes took 0ms
09:14:58.039 Slow query took 28ms: SELECT *, LENGTH(content) AS contentLength FROM blobs WHERE blobId = ?
09:14:58.039 Slow 200 GET /api/notes/55oH20g3TTGM/blob with 3411 bytes took 28ms
09:14:58.040 200 GET /api/note-map/55oH20g3TTGM/backlink-count with 11 bytes took 0ms
09:14:58.065 Slow query took 24ms: SELECT DISTINCT value FROM attributes WHERE isDeleted = 0 AND name = ? AND type = 'label' AND value != '' ORDER BY value
09:14:58.065 Slow 200 GET /api/attribute-values/location with 29 bytes took 24ms
09:14:58.068 200 GET /api/attribute-values/tag with 69 bytes took 2ms
09:14:58.069 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:14:58.069 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:14:58.081 JS Info: Creating new CKEditor
09:14:58.367 JS Info: CKEditor state changed to ready
09:14:58.911 Slow query took 69ms: SELECT COUNT(1) FROM notes
09:14:58.929 Table counts: notes: 345, revisions: 107, attachments: 36, branches: 404, attributes: 524, etapi_tokens: 0, blobs: 280
09:14:58.968 Slow query took 38ms: SELECT noteId as entityId FROM notes LEFT JOIN entity_changes ec ON ec.entityName = 'notes' AND ec.entityId = notes.noteId WHERE ec.id IS NULL
09:14:59.155 Slow query took 187ms: SELECT id, entityId FROM entity_changes LEFT JOIN notes ON entityId = notes.noteId WHERE entity_changes.isErased = 0 AND entity_changes.entityName = 'notes' AND notes.noteId IS NULL
09:14:59.233 Slow query took 25ms: SELECT id, entityId FROM entity_changes LEFT JOIN attributes ON entityId = attributes.attributeId WHERE entity_changes.isErased = 0 AND entity_changes.entityName = 'attributes' AND attributes.attributeId IS NULL
09:15:00.557 Slow query took 1283ms: SELECT notes.noteId, notes.type, notes.mime FROM notes JOIN blobs USING (blobId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
09:15:00.596 All consistency checks passed with no errors detected (took 1754ms)
09:15:00.604 200 GET /api/script/startup with 1235 bytes took 3ms
09:15:00.615 200 POST /api/tree/load with 6809 bytes took 0ms
09:15:00.623 [Script HQKpNp5ei6Gx] ERROR: Execution of script "setupButton.js" (HQKpNp5ei6Gx) failed with error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
09:15:00.624 200 POST /api/script/exec with 151 bytes took 3ms
09:15:00.625 JS Error: Uncaught error: Message: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script', Line: undefined, Column: undefined, Error object: {}, Stack: Error: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
    at I.__runOnBackendInner (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:334776)
    at async I.runOnBackend (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:335003)
    at async setupButton (eval at <anonymous> (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:310232), <anonymous>:13:5)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:15:00.886 JS Error: Uncaught error: Message: Failed to fetch, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: Failed to fetch
    at h.fetchLatestVersion (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:17226)
    at h.updateVersionStatus (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:16911)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:15:02.810 200 GET /api/tree?subTreeNoteId=vujQeSfGtnn3 with 11145 bytes took 0ms
09:15:03.016 204 PUT /api/branches/VWnWy7ThPxvU_vujQeSfGtnn3/expanded/1 with 0 bytes took 1ms
09:15:03.942 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:15:03.942 200 GET /api/note-map/p1Ftg7oz6TA7/backlink-count with 11 bytes took 0ms
09:15:03.952 204 PUT /api/options with 0 bytes took 3ms
09:15:06.005 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:15:06.006 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 0ms
09:15:06.012 204 PUT /api/options with 0 bytes took 0ms
09:15:06.035 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 1ms
09:15:06.548 200 GET /api/notes/vujQeSfGtnn3/blob with 155 bytes took 0ms
09:15:06.549 200 GET /api/note-map/vujQeSfGtnn3/backlink-count with 11 bytes took 0ms
09:15:06.671 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 0ms
09:15:06.675 200 GET /api/notes/mOyqy6wj9zx5/blob with 155 bytes took 0ms
09:15:06.676 200 POST /api/tree/load with 14818 bytes took 0ms
09:15:06.679 200 GET /api/notes/mnaPGMnRdeeg/blob with 155 bytes took 1ms
09:15:06.681 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:15:06.683 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 0ms
09:15:06.684 200 GET /api/notes/gHNlo2mku4uj/blob with 155 bytes took 0ms
09:15:06.693 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 0ms
09:15:06.695 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 0ms
09:15:07.019 204 PUT /api/options with 0 bytes took 5ms
09:15:11.657 200 GET /api/notes/vujQeSfGtnn3/blob with 155 bytes took 0ms
09:15:18.175 200 GET /api/notes/55oH20g3TTGM/blob with 3411 bytes took 0ms
09:15:18.176 200 GET /api/note-map/55oH20g3TTGM/backlink-count with 11 bytes took 0ms
09:15:18.177 200 GET /api/attribute-values/location with 29 bytes took 0ms
09:15:18.177 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:15:18.178 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:15:18.178 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:15:18.186 204 PUT /api/options with 0 bytes took 1ms
09:17:45.725 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:17:45.726 200 GET /api/note-map/p1Ftg7oz6TA7/backlink-count with 11 bytes took 0ms
09:17:45.735 204 PUT /api/options with 0 bytes took 2ms
09:17:49.158 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 1ms
09:17:49.158 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 0ms
09:17:49.166 204 PUT /api/options with 0 bytes took 2ms
09:17:49.193 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 1ms
09:17:50.532 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:17:54.515 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:17:54.516 200 GET /api/note-map/p1Ftg7oz6TA7/backlink-count with 11 bytes took 0ms
09:17:54.522 204 PUT /api/options with 0 bytes took 1ms
09:17:56.015 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:18:04.567 Slow query took 41ms: INSERT INTO notes (noteId, title, isProtected, type, mime, blobId, isDeleted, dateCreated, dateModified, utcDateCreated, utcDateModified) VALUES (@noteId, @title, @isProtected, @type, @mime, @blobId, @isDeleted, @dateCreated, @dateModified, @utcDateCreated, @utcDateModified) ON CONFLICT (noteId) DO UPDATE SET noteId = @noteId, title = @title, isProtected = @isProtected, type = @type, mime = @mime, blobId = @blobId, isDeleted = @isDeleted, dateCreated = @dateCreated, dateModified = @dateModified, utcDateCreated = @utcDateCreated, utcDateModified = @utcDateModified
09:18:04.592 Created new note 'nYv8wlV36SAm', branch '0CT0qOxhqJMh_nYv8wlV36SAm' of type 'text', mime 'text/html'
09:18:04.595 Slow 200 POST /api/notes/0CT0qOxhqJMh/children?target=into&targetBranchId= with 554 bytes took 76ms
09:18:04.599 200 POST /api/tree/load with 10828 bytes took 1ms
09:18:04.604 200 GET /api/tree?subTreeNoteId=nYv8wlV36SAm with 10828 bytes took 1ms
09:18:04.644 200 GET /api/notes/nYv8wlV36SAm/blob with 3244 bytes took 0ms
09:18:04.645 200 GET /api/note-map/nYv8wlV36SAm/backlink-count with 11 bytes took 0ms
09:18:04.645 200 GET /api/attribute-values/location with 29 bytes took 0ms
09:18:04.646 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:18:04.657 204 PUT /api/options with 0 bytes took 0ms
09:18:07.371 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 1ms
09:18:07.378 200 GET /api/notes/nYv8wlV36SAm/blob with 3244 bytes took 0ms
09:18:09.393 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 1ms
09:18:09.404 200 GET /api/notes/nYv8wlV36SAm/blob with 3244 bytes took 1ms
09:18:10.133 Slow query took 20ms: SELECT revisionId FROM revisions WHERE noteId = ? AND utcDateCreated >= ?
09:18:10.136 Slow 204 PUT /api/notes/nYv8wlV36SAm/data with 0 bytes took 23ms
09:18:10.140 200 GET /api/notes/nYv8wlV36SAm/blob with 511 bytes took 0ms
09:18:10.905 200 GET /api/notes/nYv8wlV36SAm/blob with 511 bytes took 1ms
09:18:11.136 204 PUT /api/notes/nYv8wlV36SAm/data with 0 bytes took 9ms
09:18:11.159 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 1ms
09:18:11.352 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 0ms
09:18:11.353 200 GET /api/note-map/aozr7mKzQRZ7/backlink-count with 11 bytes took 0ms
09:18:11.353 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:18:11.354 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:18:11.354 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:18:11.362 204 PUT /api/options with 0 bytes took 1ms
09:18:11.534 200 POST /api/tree/load with 15956 bytes took 1ms
09:18:11.553 200 GET /api/notes/SqiDsd3Dprim/blob with 4836 bytes took 1ms
09:18:12.502 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:18:12.503 200 GET /api/note-map/nYv8wlV36SAm/backlink-count with 11 bytes took 0ms
09:18:12.503 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:18:12.504 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:18:12.511 204 PUT /api/options with 0 bytes took 1ms
09:18:16.087 200 GET /api/notes/55oH20g3TTGM/blob with 3411 bytes took 0ms
09:18:16.088 200 GET /api/note-map/55oH20g3TTGM/backlink-count with 11 bytes took 0ms
09:18:16.089 200 GET /api/attribute-values/location with 41 bytes took 1ms
09:18:16.089 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:18:16.091 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:18:16.091 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:18:16.097 204 PUT /api/options with 0 bytes took 1ms
09:18:22.162 204 PUT /api/branches/VWnWy7ThPxvU_0CT0qOxhqJMh/expanded/0 with 0 bytes took 1ms
09:18:22.557 200 GET /api/notes/1dwiifQICfV4/blob with 155 bytes took 0ms
09:18:22.558 200 GET /api/note-map/1dwiifQICfV4/backlink-count with 11 bytes took 1ms
09:18:22.564 204 PUT /api/options with 0 bytes took 1ms
09:18:22.605 200 GET /api/notes/VWnWy7ThPxvU/blob with 3981 bytes took 0ms
09:18:22.610 200 GET /api/notes/DEBw3gn9gBI9/blob with 2291 bytes took 0ms
09:18:22.630 200 POST /api/tree/load with 6327 bytes took 0ms
09:18:22.633 200 GET /api/notes/lWL9tYjhWoTt/blob with 1505 bytes took 0ms
09:18:22.636 200 GET /api/notes/WM5B1BCkVIHE/blob with 155 bytes took 0ms
09:18:22.636 200 POST /api/tree/load with 6297 bytes took 0ms
09:18:22.638 200 GET /api/notes/kBbCKspw2J2x/blob with 223 bytes took 0ms
09:18:22.640 200 GET /api/notes/8I4ySlfCLfVx/blob with 212 bytes took 1ms
09:18:24.301 200 GET /api/notes/vujQeSfGtnn3/blob with 155 bytes took 1ms
09:18:24.301 200 GET /api/note-map/vujQeSfGtnn3/backlink-count with 11 bytes took 0ms
09:18:24.310 204 PUT /api/options with 0 bytes took 3ms
09:18:24.426 200 GET /api/notes/mOyqy6wj9zx5/blob with 155 bytes took 1ms
09:18:24.427 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 0ms
09:18:24.429 200 GET /api/notes/mnaPGMnRdeeg/blob with 155 bytes took 0ms
09:18:24.436 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:18:24.438 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:18:24.440 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 1ms
09:18:24.441 200 GET /api/notes/gHNlo2mku4uj/blob with 155 bytes took 0ms
09:18:24.442 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 0ms
09:18:24.443 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 0ms
09:18:25.484 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:18:25.485 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 0ms
09:18:25.492 204 PUT /api/options with 0 bytes took 1ms
09:18:25.610 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 1ms
09:18:58.007 DB size: 5029 KB
09:18:58.102 Becca (note cache) load took 86ms
09:18:58.129 {
  "appVersion": "0.91.6",
  "dbVersion": 228,
  "nodeVersion": "v20.18.1",
  "syncVersion": 34,
  "buildDate": "2025-02-03T17:08:57Z",
  "buildRevision": "79e830b6ea22e51196bdca4c021f30ecfad92723",
  "dataDirectory": "Z:\\Radchenko\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2025-03-07T06:18:57.024Z"
}
09:18:58.130 CPU model: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, logical cores: 8, freq: 4008 Mhz
09:18:58.130 Trusted reverse proxy: false
09:18:58.130 App HTTP server starting up at port 37840
09:18:58.133 Listening on port 37840
09:18:58.361 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
09:18:59.037 CSRF token generation: Successful
09:18:59.918 200 GET /api/options with 8463 bytes took 0ms
09:18:59.921 200 GET /api/keyboard-actions with 14449 bytes took 2ms
09:18:59.923 200 GET /api/tree with 77795 bytes took 2ms
09:19:00.154 200 GET /api/script/widgets with 2 bytes took 1ms
09:19:00.315 200 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 1ms
09:19:00.321 200 GET /api/tree?subTreeNoteId=7E2MquCh56bK with 8032 bytes took 0ms
09:19:00.322 200 GET /api/tree?subTreeNoteId=_lbMobileAvailableLaunchers with 4379 bytes took 0ms
09:19:00.699 Slow 200 GET /api/notes/Hl8cw7PNHA5w/blob with 12184 bytes took 10ms
09:19:00.989 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 2ms
09:19:00.990 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 1ms
09:19:01.031 JS Info: Creating new CKEditor
09:19:01.286 JS Info: CKEditor state changed to ready
09:19:01.410 200 POST /api/tree/load with 15818 bytes took 1ms
09:19:01.416 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 2ms
09:19:02.140 Table counts: notes: 346, revisions: 107, attachments: 36, branches: 405, attributes: 529, etapi_tokens: 0, blobs: 281
09:19:02.269 Slow query took 113ms: SELECT id, entityId FROM entity_changes LEFT JOIN notes ON entityId = notes.noteId WHERE entity_changes.isErased = 0 AND entity_changes.entityName = 'notes' AND notes.noteId IS NULL
09:19:02.500 Slow query took 125ms: SELECT notes.noteId, notes.type, notes.mime FROM notes JOIN blobs USING (blobId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
09:19:02.536 All consistency checks passed with no errors detected (took 425ms)
09:19:02.539 200 GET /api/script/startup with 1235 bytes took 1ms
09:19:02.546 200 POST /api/tree/load with 6809 bytes took 1ms
09:19:02.550 [Script HQKpNp5ei6Gx] ERROR: Execution of script "setupButton.js" (HQKpNp5ei6Gx) failed with error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
09:19:02.551 200 POST /api/script/exec with 151 bytes took 2ms
09:19:02.552 JS Error: Uncaught error: Message: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script', Line: undefined, Column: undefined, Error object: {}, Stack: Error: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
    at I.__runOnBackendInner (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:334776)
    at async I.runOnBackend (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:335003)
    at async setupButton (eval at <anonymous> (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:310232), <anonymous>:13:5)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:19:03.858 JS Error: Uncaught error: Message: Failed to fetch, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: Failed to fetch
    at h.fetchLatestVersion (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:17226)
    at h.updateVersionStatus (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:16911)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:19:04.246 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:19:04.247 200 GET /api/note-map/p1Ftg7oz6TA7/backlink-count with 11 bytes took 0ms
09:19:04.270 Slow 204 PUT /api/options with 0 bytes took 17ms
09:19:06.130 200 GET /api/tree?subTreeNoteId=0CT0qOxhqJMh with 19480 bytes took 1ms
09:19:06.350 204 PUT /api/branches/VWnWy7ThPxvU_0CT0qOxhqJMh/expanded/1 with 0 bytes took 2ms
09:19:06.769 200 GET /api/tree?subTreeNoteId=2KcJzqkjwZIC with 18077 bytes took 0ms
09:19:06.983 204 PUT /api/branches/VWnWy7ThPxvU_2KcJzqkjwZIC/expanded/1 with 0 bytes took 0ms
09:19:08.798 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:19:08.799 200 GET /api/note-map/nYv8wlV36SAm/backlink-count with 11 bytes took 0ms
09:19:08.800 200 GET /api/attribute-values/location with 41 bytes took 1ms
09:19:08.800 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:19:08.810 204 PUT /api/options with 0 bytes took 0ms
09:19:10.263 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 1ms
09:19:10.263 200 GET /api/note-map/YTUHfcafiY4A/backlink-count with 11 bytes took 0ms
09:19:10.270 204 PUT /api/options with 0 bytes took 1ms
09:19:10.756 200 GET /api/notes/p1Ftg7oz6TA7/blob with 155 bytes took 0ms
09:19:10.757 200 GET /api/note-map/p1Ftg7oz6TA7/backlink-count with 11 bytes took 0ms
09:19:11.280 204 PUT /api/options with 0 bytes took 6ms
09:19:12.967 200 GET /api/search-templates with 31 bytes took 1ms
09:19:12.967 200 POST /api/tree/load with 8243 bytes took 0ms
09:19:12.969 200 GET /api/search-templates with 31 bytes took 0ms
09:19:14.802 200 POST /api/delete-notes-preview with 60 bytes took 2ms
09:19:16.157 Sending message to all clients: {"type":"taskProgressCount","taskId":"ziuK923b6X","taskType":"deleteNotes","data":null,"progressCount":0}
09:19:16.158 Marking branches vujQeSfGtnn3_p1Ftg7oz6TA7 as deleted
09:19:16.161 Deleting note 'p1Ftg7oz6TA7'
09:19:16.161 Marking attributes GXWqrhrYJZvR as deleted
09:19:16.171 Marking notes p1Ftg7oz6TA7 as deleted
09:19:16.172 Sending message to all clients: {"type":"taskSucceeded","taskId":"ziuK923b6X","taskType":"deleteNotes","data":null}
09:19:16.173 Slow 200 DELETE /api/branches/vujQeSfGtnn3_p1Ftg7oz6TA7?taskId=ziuK923b6X&eraseNotes=false&last=true with 20 bytes took 16ms
09:19:16.175 200 GET /api/notes/vujQeSfGtnn3/blob with 155 bytes took 0ms
09:19:16.176 200 GET /api/note-map/vujQeSfGtnn3/backlink-count with 11 bytes took 0ms
09:19:16.189 204 PUT /api/options with 0 bytes took 2ms
09:19:16.326 200 GET /api/notes/mOyqy6wj9zx5/blob with 155 bytes took 0ms
09:19:16.329 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 0ms
09:19:16.330 200 GET /api/notes/mnaPGMnRdeeg/blob with 155 bytes took 0ms
09:19:16.332 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:19:16.334 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 0ms
09:19:16.335 200 GET /api/notes/gHNlo2mku4uj/blob with 155 bytes took 0ms
09:19:16.337 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 1ms
09:19:16.338 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 0ms
09:19:17.643 Created new note 'YkK4OseXXgX9', branch 'vujQeSfGtnn3_YkK4OseXXgX9' of type 'text', mime 'text/html'
09:19:17.647 Slow 200 POST /api/notes/vujQeSfGtnn3/children?target=into&targetBranchId= with 554 bytes took 42ms
09:19:17.649 200 POST /api/tree/load with 8188 bytes took 0ms
09:19:17.689 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:17.690 200 GET /api/note-map/YkK4OseXXgX9/backlink-count with 11 bytes took 0ms
09:19:17.701 204 PUT /api/options with 0 bytes took 0ms
09:19:19.659 200 PUT /api/notes/YkK4OseXXgX9/title with 320 bytes took 3ms
09:19:19.668 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:20.668 Slow 200 PUT /api/notes/YkK4OseXXgX9/title with 323 bytes took 10ms
09:19:21.663 200 PUT /api/notes/YkK4OseXXgX9/title with 325 bytes took 2ms
09:19:21.676 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:25.477 200 GET /api/notes/mnaPGMnRdeeg/blob with 155 bytes took 1ms
09:19:25.478 200 GET /api/note-map/mnaPGMnRdeeg/backlink-count with 11 bytes took 0ms
09:19:25.484 204 PUT /api/options with 0 bytes took 1ms
09:19:25.511 200 GET /api/notes/IklBmWhpvnJw/blob with 3244 bytes took 0ms
09:19:29.555 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:29.556 200 GET /api/note-map/YkK4OseXXgX9/backlink-count with 11 bytes took 1ms
09:19:29.563 204 PUT /api/options with 0 bytes took 2ms
09:19:32.498 204 PUT /api/notes/YkK4OseXXgX9/attributes with 0 bytes took 7ms
09:19:32.505 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:35.097 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:19:35.135 204 PUT /api/notes/YkK4OseXXgX9/attributes with 0 bytes took 0ms
09:19:36.885 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:19:36.886 200 GET /api/note-map/nYv8wlV36SAm/backlink-count with 11 bytes took 0ms
09:19:36.886 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:19:36.887 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:19:36.895 204 PUT /api/options with 0 bytes took 2ms
09:19:38.417 Marking attributes UlcBDtSv69kt as deleted
09:19:38.418 204 DELETE /api/notes/nYv8wlV36SAm/attributes/UlcBDtSv69kt with 0 bytes took 1ms
09:19:38.419 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:19:38.428 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:19:39.716 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 2ms
09:19:39.721 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:19:41.117 200 GET /api/notes/mOyqy6wj9zx5/blob with 155 bytes took 1ms
09:19:41.117 200 GET /api/note-map/mOyqy6wj9zx5/backlink-count with 11 bytes took 0ms
09:19:41.125 204 PUT /api/options with 0 bytes took 1ms
09:19:41.141 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 1ms
09:19:41.146 200 GET /api/notes/IklBmWhpvnJw/blob with 3244 bytes took 0ms
09:19:41.757 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 0ms
09:19:41.757 200 GET /api/note-map/Vvcm7K4kkyEI/backlink-count with 11 bytes took 0ms
09:19:42.139 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 0ms
09:19:42.140 200 GET /api/note-map/BY2T709E0LfR/backlink-count with 11 bytes took 0ms
09:19:42.147 204 PUT /api/options with 0 bytes took 1ms
09:19:45.284 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:19:48.347 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:19:48.348 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 0ms
09:19:48.354 204 PUT /api/options with 0 bytes took 0ms
09:19:48.373 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 1ms
09:19:49.404 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:19:52.820 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 1ms
09:19:52.820 200 GET /api/note-map/YkK4OseXXgX9/backlink-count with 11 bytes took 0ms
09:19:52.827 204 PUT /api/options with 0 bytes took 1ms
09:19:54.747 Created new note 'MWZsqLQoVJbD', branch '0CT0qOxhqJMh_MWZsqLQoVJbD' of type 'text', mime 'text/html'
09:19:54.753 Slow 200 POST /api/notes/0CT0qOxhqJMh/children?target=into&targetBranchId= with 554 bytes took 23ms
09:19:54.756 200 POST /api/tree/load with 10973 bytes took 1ms
09:19:54.759 200 GET /api/tree?subTreeNoteId=MWZsqLQoVJbD with 10973 bytes took 0ms
09:19:54.799 200 GET /api/notes/MWZsqLQoVJbD/blob with 3244 bytes took 0ms
09:19:54.799 200 GET /api/note-map/MWZsqLQoVJbD/backlink-count with 11 bytes took 0ms
09:19:54.800 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:19:54.800 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:19:54.814 204 PUT /api/options with 0 bytes took 1ms
09:19:57.322 200 PUT /api/notes/MWZsqLQoVJbD/attribute with 30 bytes took 1ms
09:19:57.328 200 GET /api/notes/MWZsqLQoVJbD/blob with 3244 bytes took 0ms
09:20:00.018 200 PUT /api/notes/MWZsqLQoVJbD/attribute with 30 bytes took 1ms
09:20:00.026 200 GET /api/notes/MWZsqLQoVJbD/blob with 3244 bytes took 1ms
09:20:01.186 200 PUT /api/notes/MWZsqLQoVJbD/title with 322 bytes took 4ms
09:20:01.192 200 GET /api/notes/MWZsqLQoVJbD/blob with 3244 bytes took 0ms
09:20:01.810 200 PUT /api/notes/MWZsqLQoVJbD/title with 326 bytes took 1ms
09:20:03.516 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 0ms
09:20:03.517 200 GET /api/note-map/jKw9VammVuPf/backlink-count with 11 bytes took 1ms
09:20:03.523 204 PUT /api/options with 0 bytes took 0ms
09:20:10.287 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 0ms
09:20:10.287 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:20:10.300 204 PUT /api/options with 0 bytes took 1ms
09:20:15.132 200 GET /api/notes/DEBw3gn9gBI9/blob with 2291 bytes took 1ms
09:20:15.132 200 GET /api/note-map/DEBw3gn9gBI9/backlink-count with 11 bytes took 0ms
09:20:15.142 204 PUT /api/options with 0 bytes took 1ms
09:51:13.823 DB size: 5029 KB
09:51:13.937 Becca (note cache) load took 104ms
09:51:13.987 {
  "appVersion": "0.91.6",
  "dbVersion": 228,
  "nodeVersion": "v20.18.1",
  "syncVersion": 34,
  "buildDate": "2025-02-03T17:08:57Z",
  "buildRevision": "79e830b6ea22e51196bdca4c021f30ecfad92723",
  "dataDirectory": "Z:\\Radchenko\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2025-03-07T06:51:12.847Z"
}
09:51:13.988 CPU model: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, logical cores: 8, freq: 4008 Mhz
09:51:13.988 Trusted reverse proxy: false
09:51:13.989 App HTTP server starting up at port 37840
09:51:13.994 Listening on port 37840
09:51:14.225 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
09:51:14.907 CSRF token generation: Successful
09:51:15.754 200 GET /api/options with 8437 bytes took 1ms
09:51:15.757 200 GET /api/keyboard-actions with 14449 bytes took 2ms
09:51:15.759 200 GET /api/tree with 90397 bytes took 2ms
09:51:15.992 200 GET /api/script/widgets with 2 bytes took 2ms
09:51:16.152 200 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 0ms
09:51:16.158 200 GET /api/tree?subTreeNoteId=7E2MquCh56bK with 8032 bytes took 0ms
09:51:16.159 200 GET /api/tree?subTreeNoteId=_lbMobileAvailableLaunchers with 4379 bytes took 0ms
09:51:16.534 Slow 200 GET /api/notes/Hl8cw7PNHA5w/blob with 12184 bytes took 11ms
09:51:16.829 Slow 200 GET /api/notes/DEBw3gn9gBI9/blob with 2291 bytes took 17ms
09:51:16.830 200 GET /api/note-map/DEBw3gn9gBI9/backlink-count with 11 bytes took 0ms
09:51:17.986 Table counts: notes: 348, revisions: 107, attachments: 36, branches: 407, attributes: 536, etapi_tokens: 0, blobs: 281
09:51:18.116 Slow query took 114ms: SELECT id, entityId FROM entity_changes LEFT JOIN notes ON entityId = notes.noteId WHERE entity_changes.isErased = 0 AND entity_changes.entityName = 'notes' AND notes.noteId IS NULL
09:51:18.355 Slow query took 133ms: SELECT notes.noteId, notes.type, notes.mime FROM notes JOIN blobs USING (blobId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
09:51:18.394 All consistency checks passed with no errors detected (took 438ms)
09:51:18.399 200 GET /api/script/startup with 1235 bytes took 3ms
09:51:18.402 200 POST /api/tree/load with 6809 bytes took 1ms
09:51:18.409 [Script HQKpNp5ei6Gx] ERROR: Execution of script "setupButton.js" (HQKpNp5ei6Gx) failed with error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
09:51:18.409 200 POST /api/script/exec with 151 bytes took 3ms
09:51:18.411 JS Error: Uncaught error: Message: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script', Line: undefined, Column: undefined, Error object: {}, Stack: Error: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
    at I.__runOnBackendInner (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:334776)
    at async I.runOnBackend (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:335003)
    at async setupButton (eval at <anonymous> (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:310232), <anonymous>:13:5)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:51:19.759 JS Error: Uncaught error: Message: Failed to fetch, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: Failed to fetch
    at h.fetchLatestVersion (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:17226)
    at h.updateVersionStatus (http://127.0.0.1:37840/assets/v0.91.6/app-dist/86.js:1:16911)
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:51:21.459 200 GET /api/notes/55oH20g3TTGM/blob with 3411 bytes took 2ms
09:51:21.460 200 GET /api/note-map/55oH20g3TTGM/backlink-count with 11 bytes took 0ms
09:51:21.461 200 GET /api/attribute-values/location with 41 bytes took 1ms
09:51:21.461 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:51:21.462 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:51:21.462 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:51:21.532 Slow query took 59ms: INSERT OR REPLACE INTO entity_changes ( entityName, entityId, hash, isErased, utcDateChanged, isSynced, changeId, componentId, instanceId ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
09:51:21.540 Slow 204 PUT /api/options with 0 bytes took 68ms
09:51:21.541 JS Info: Creating new CKEditor
09:51:21.806 JS Info: CKEditor state changed to ready
09:51:24.542 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 1ms
09:51:24.542 200 GET /api/note-map/YkK4OseXXgX9/backlink-count with 11 bytes took 0ms
09:51:24.577 Slow 204 PUT /api/options with 0 bytes took 27ms
09:51:25.301 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 0ms
09:51:25.302 200 GET /api/note-map/nYv8wlV36SAm/backlink-count with 11 bytes took 1ms
09:51:25.302 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:51:25.303 200 GET /api/attribute-values/tag with 69 bytes took 1ms
09:51:25.553 204 PUT /api/options with 0 bytes took 1ms
09:51:27.867 Slow 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 11ms
09:51:27.872 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 1ms
09:51:30.298 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 1ms
09:51:30.305 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 1ms
09:51:32.170 200 PUT /api/notes/nYv8wlV36SAm/attribute with 30 bytes took 5ms
09:51:32.195 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 1ms
09:51:32.241 200 GET /api/tree?subTreeNoteId=mnaPGMnRdeeg with 14817 bytes took 1ms
09:51:32.459 204 PUT /api/branches/vujQeSfGtnn3_mnaPGMnRdeeg/expanded/1 with 0 bytes took 1ms
09:51:34.252 200 GET /api/notes/0CT0qOxhqJMh/blob with 155 bytes took 0ms
09:51:34.253 200 GET /api/note-map/0CT0qOxhqJMh/backlink-count with 11 bytes took 0ms
09:51:34.267 204 PUT /api/options with 0 bytes took 8ms
09:51:34.287 200 GET /api/notes/APrHsfLfCVMe/blob with 3244 bytes took 0ms
09:51:34.292 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 0ms
09:51:34.302 200 GET /api/notes/55oH20g3TTGM/blob with 3411 bytes took 1ms
09:51:34.304 200 GET /api/notes/nYv8wlV36SAm/blob with 516 bytes took 1ms
09:51:34.305 200 GET /api/notes/MWZsqLQoVJbD/blob with 3244 bytes took 0ms
09:51:37.751 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 1ms
09:51:37.751 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:51:37.764 204 PUT /api/options with 0 bytes took 0ms
09:51:40.273 200 POST /api/tree/load with 7358 bytes took 1ms
09:51:50.068 204 PUT /api/notes/xaBN7igPwmRv/attributes with 0 bytes took 0ms
09:51:50.069 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:51:53.738 Slow 204 PUT /api/notes/xaBN7igPwmRv/type with 0 bytes took 19ms
09:51:53.743 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 0ms
09:51:53.759 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:51:58.026 204 PUT /api/notes/xaBN7igPwmRv/type with 0 bytes took 3ms
09:51:58.032 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 0ms
09:51:58.049 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 1ms
09:52:02.888 204 PUT /api/notes/xaBN7igPwmRv/type with 0 bytes took 0ms
09:52:02.897 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 0ms
09:52:02.912 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:52:06.084 204 PUT /api/notes/xaBN7igPwmRv/type with 0 bytes took 5ms
09:52:06.090 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 1ms
09:52:06.105 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:52:08.075 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:52:08.076 200 GET /api/note-map/YkK4OseXXgX9/backlink-count with 11 bytes took 1ms
09:52:08.081 204 PUT /api/options with 0 bytes took 0ms
09:52:09.083 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 0ms
09:52:09.084 200 GET /api/note-map/BY2T709E0LfR/backlink-count with 11 bytes took 1ms
09:52:09.091 204 PUT /api/options with 0 bytes took 1ms
09:52:09.692 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 0ms
09:52:09.693 200 GET /api/note-map/Vvcm7K4kkyEI/backlink-count with 11 bytes took 0ms
09:52:10.104 204 PUT /api/options with 0 bytes took 2ms
09:52:10.323 200 GET /api/notes/gHNlo2mku4uj/blob with 155 bytes took 0ms
09:52:10.324 200 GET /api/note-map/gHNlo2mku4uj/backlink-count with 11 bytes took 1ms
09:52:10.763 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 0ms
09:52:10.763 200 GET /api/note-map/YTUHfcafiY4A/backlink-count with 11 bytes took 0ms
09:52:11.103 204 PUT /api/options with 0 bytes took 1ms
09:52:11.287 200 GET /api/note-map/YTUHfcafiY4A/backlink-count with 11 bytes took 0ms
09:52:11.806 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:52:11.807 200 GET /api/note-map/DwM9085iO6L7/backlink-count with 11 bytes took 0ms
09:52:11.838 200 GET /api/notes/aozr7mKzQRZ7/blob with 3454 bytes took 0ms
09:52:12.110 204 PUT /api/options with 0 bytes took 5ms
09:52:12.288 200 GET /api/notes/IklBmWhpvnJw/blob with 3244 bytes took 0ms
09:52:12.289 200 GET /api/note-map/IklBmWhpvnJw/backlink-count with 11 bytes took 0ms
09:52:12.290 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:52:12.290 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:52:13.111 204 PUT /api/options with 0 bytes took 1ms
09:52:13.997 200 GET /api/notes/vujQeSfGtnn3/blob with 155 bytes took 1ms
09:52:13.997 200 GET /api/note-map/vujQeSfGtnn3/backlink-count with 11 bytes took 0ms
09:52:14.028 200 GET /api/notes/mnaPGMnRdeeg/blob with 155 bytes took 0ms
09:52:14.033 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 0ms
09:52:14.035 200 GET /api/notes/mOyqy6wj9zx5/blob with 155 bytes took 1ms
09:52:14.036 200 GET /api/notes/DwM9085iO6L7/blob with 155 bytes took 0ms
09:52:14.038 200 GET /api/notes/YTUHfcafiY4A/blob with 155 bytes took 0ms
09:52:14.039 200 GET /api/notes/gHNlo2mku4uj/blob with 155 bytes took 0ms
09:52:14.041 200 GET /api/notes/Vvcm7K4kkyEI/blob with 155 bytes took 1ms
09:52:14.050 200 GET /api/notes/BY2T709E0LfR/blob with 155 bytes took 1ms
09:52:14.051 200 GET /api/notes/YkK4OseXXgX9/blob with 155 bytes took 0ms
09:52:14.111 204 PUT /api/options with 0 bytes took 1ms
09:52:15.617 200 GET /api/tree?subTreeNoteId=mOyqy6wj9zx5 with 18787 bytes took 1ms
09:52:15.827 204 PUT /api/branches/vujQeSfGtnn3_mOyqy6wj9zx5/expanded/1 with 0 bytes took 0ms
09:52:22.432 204 PUT /api/branches/vujQeSfGtnn3_mOyqy6wj9zx5/expanded/0 with 0 bytes took 0ms
09:52:22.798 200 GET /api/notes/jKw9VammVuPf/blob with 3244 bytes took 1ms
09:52:22.798 200 GET /api/note-map/jKw9VammVuPf/backlink-count with 11 bytes took 0ms
09:52:22.805 204 PUT /api/options with 0 bytes took 1ms
09:52:24.468 204 PUT /api/branches/VWnWy7ThPxvU_vujQeSfGtnn3/expanded/0 with 0 bytes took 0ms
09:52:25.888 200 GET /api/tree?subTreeNoteId=9p9bBdBKp2tV with 8933 bytes took 0ms
09:52:26.102 204 PUT /api/branches/1dwiifQICfV4_9p9bBdBKp2tV/expanded/1 with 0 bytes took 1ms
09:52:27.507 200 GET /api/note-map/1j3ZJHmSCDRa/backlink-count with 11 bytes took 0ms
09:52:27.519 204 PUT /api/options with 0 bytes took 1ms
09:52:28.348 200 GET /api/note-map/gje2hMDwSopO/backlink-count with 11 bytes took 0ms
09:52:28.521 204 PUT /api/options with 0 bytes took 0ms
09:52:28.772 200 GET /api/note-map/znjBlUe9QFeX/backlink-count with 11 bytes took 0ms
09:52:29.526 204 PUT /api/options with 0 bytes took 2ms
09:52:29.766 200 GET /api/note-map/LdDCIbfMhzv1/backlink-count with 11 bytes took 0ms
09:52:30.527 204 PUT /api/options with 0 bytes took 2ms
09:52:34.792 204 PUT /api/branches/VWnWy7ThPxvU_2KcJzqkjwZIC/expanded/0 with 0 bytes took 0ms
09:52:35.545 204 PUT /api/branches/VWnWy7ThPxvU_0CT0qOxhqJMh/expanded/0 with 0 bytes took 1ms
09:52:36.160 204 PUT /api/branches/1dwiifQICfV4_VWnWy7ThPxvU/expanded/0 with 0 bytes took 1ms
09:52:37.044 204 PUT /api/branches/1dwiifQICfV4_VWnWy7ThPxvU/expanded/1 with 0 bytes took 0ms
09:52:37.878 204 PUT /api/branches/1dwiifQICfV4_VWnWy7ThPxvU/expanded/0 with 0 bytes took 1ms
09:52:39.108 200 GET /api/notes/DEBw3gn9gBI9/blob with 2291 bytes took 1ms
09:52:39.108 200 GET /api/note-map/DEBw3gn9gBI9/backlink-count with 11 bytes took 0ms
09:52:39.117 204 PUT /api/options with 0 bytes took 1ms
09:52:45.534 204 PUT /api/branches/1dwiifQICfV4_VWnWy7ThPxvU/expanded/1 with 0 bytes took 0ms
09:52:46.661 200 GET /api/notes/xaBN7igPwmRv/blob with 448 bytes took 1ms
09:52:46.661 200 GET /api/note-map/xaBN7igPwmRv/backlink-count with 11 bytes took 0ms
09:52:46.675 204 PUT /api/options with 0 bytes took 1ms
09:52:49.193 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:52:52.983 200 GET /api/notes/pDb6wWYyOJXE/blob with 155 bytes took 1ms
09:52:52.983 200 GET /api/note-map/pDb6wWYyOJXE/backlink-count with 11 bytes took 0ms
09:52:52.991 204 PUT /api/options with 0 bytes took 2ms
09:52:53.022 200 POST /api/tree/load with 7764 bytes took 1ms
09:52:53.027 200 GET /api/notes/ijZApaI5mD8G/blob with 3244 bytes took 0ms
09:52:53.029 200 GET /api/notes/WRKNlikAO2k1/blob with 2257 bytes took 0ms
09:52:53.043 200 GET /api/notes/jBoktbf8XwIC/blob with 311 bytes took 0ms
09:52:53.071 200 GET /api/notes/qB0nK4lKy82R/blob with 720 bytes took 0ms
09:52:55.248 200 GET /api/tree?subTreeNoteId=bGNckHLlFh6u with 8858 bytes took 0ms
09:52:55.459 204 PUT /api/branches/VWnWy7ThPxvU_bGNckHLlFh6u/expanded/1 with 0 bytes took 0ms
09:52:56.841 200 GET /api/tree?subTreeNoteId=y5Qya1gyEBnS with 12841 bytes took 0ms
09:52:57.060 204 PUT /api/branches/bGNckHLlFh6u_y5Qya1gyEBnS/expanded/1 with 0 bytes took 0ms
09:52:57.894 204 PUT /api/branches/bGNckHLlFh6u_y5Qya1gyEBnS/expanded/0 with 0 bytes took 0ms
09:52:59.153 200 GET /api/tree?subTreeNoteId=pDb6wWYyOJXE with 9419 bytes took 1ms
09:52:59.364 204 PUT /api/branches/VWnWy7ThPxvU_pDb6wWYyOJXE/expanded/1 with 0 bytes took 0ms
09:53:00.599 200 GET /api/notes/WRKNlikAO2k1/blob with 2257 bytes took 1ms
09:53:00.599 200 GET /api/note-map/WRKNlikAO2k1/backlink-count with 11 bytes took 0ms
09:53:00.618 204 PUT /api/options with 0 bytes took 1ms
09:53:11.207 204 PUT /api/notes/WRKNlikAO2k1/attributes with 0 bytes took 1ms
09:53:11.550 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:53:14.344 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:53:14.352 204 PUT /api/notes/WRKNlikAO2k1/attributes with 0 bytes took 0ms
09:53:16.286 200 GET /api/notes/jBoktbf8XwIC/blob with 311 bytes took 1ms
09:53:16.286 200 GET /api/note-map/jBoktbf8XwIC/backlink-count with 11 bytes took 0ms
09:53:16.301 204 PUT /api/options with 0 bytes took 1ms
09:53:18.012 200 GET /api/notes/ijZApaI5mD8G/blob with 3244 bytes took 1ms
09:53:18.012 200 GET /api/note-map/ijZApaI5mD8G/backlink-count with 12 bytes took 0ms
09:53:18.013 200 GET /api/attribute-values/location with 41 bytes took 1ms
09:53:18.013 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:53:18.021 204 PUT /api/options with 0 bytes took 1ms
09:53:18.525 200 GET /api/notes/qB0nK4lKy82R/blob with 720 bytes took 0ms
09:53:18.526 200 GET /api/note-map/qB0nK4lKy82R/backlink-count with 11 bytes took 1ms
09:53:19.027 204 PUT /api/options with 0 bytes took 3ms
09:53:23.344 200 GET /api/notes/qB0nK4lKy82R/blob with 720 bytes took 1ms
09:53:23.351 204 PUT /api/notes/qB0nK4lKy82R/attributes with 0 bytes took 0ms
09:53:31.581 200 GET /api/notes/ijZApaI5mD8G/blob with 3244 bytes took 1ms
09:53:31.581 200 GET /api/note-map/ijZApaI5mD8G/backlink-count with 12 bytes took 0ms
09:53:31.582 200 GET /api/attribute-values/location with 41 bytes took 1ms
09:53:31.582 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:53:31.590 204 PUT /api/options with 0 bytes took 1ms
09:53:32.339 200 GET /api/notes/jBoktbf8XwIC/blob with 311 bytes took 1ms
09:53:32.339 200 GET /api/note-map/jBoktbf8XwIC/backlink-count with 11 bytes took 0ms
09:53:32.590 204 PUT /api/options with 0 bytes took 0ms
09:53:36.716 200 GET /api/notes/ijZApaI5mD8G/blob with 3244 bytes took 0ms
09:53:36.716 200 GET /api/note-map/ijZApaI5mD8G/backlink-count with 12 bytes took 0ms
09:53:36.716 200 GET /api/attribute-values/location with 41 bytes took 0ms
09:53:36.717 200 GET /api/attribute-values/tag with 69 bytes took 0ms
09:53:36.725 204 PUT /api/options with 0 bytes took 1ms
09:53:38.362 200 GET /api/notes/jBoktbf8XwIC/blob with 311 bytes took 0ms
09:53:38.362 200 GET /api/note-map/jBoktbf8XwIC/backlink-count with 11 bytes took 0ms
09:53:38.373 204 PUT /api/options with 0 bytes took 1ms
09:53:38.777 200 GET /api/notes/WRKNlikAO2k1/blob with 2257 bytes took 1ms
09:53:38.777 200 GET /api/note-map/WRKNlikAO2k1/backlink-count with 11 bytes took 0ms
09:53:38.878 200 POST /api/tree/load with 7673 bytes took 0ms
09:53:38.885 200 GET /api/notes/VuvzR0VspDw6/blob with 1098 bytes took 0ms
09:53:39.383 204 PUT /api/options with 0 bytes took 3ms
09:53:39.472 200 GET /api/tree?subTreeNoteId=WRKNlikAO2k1 with 7673 bytes took 0ms
09:53:39.678 204 PUT /api/branches/pDb6wWYyOJXE_WRKNlikAO2k1/expanded/1 with 0 bytes took 1ms
09:53:40.108 200 GET /api/notes/VuvzR0VspDw6/blob with 1098 bytes took 1ms
09:53:40.108 200 GET /api/note-map/VuvzR0VspDw6/backlink-count with 11 bytes took 0ms
09:53:40.386 204 PUT /api/options with 0 bytes took 2ms
09:53:45.139 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:53:45.139 204 PUT /api/notes/VuvzR0VspDw6/attributes with 0 bytes took 0ms
09:53:46.304 JS Error: Uncaught error: Message: o.focus is not a function, Line: undefined, Column: undefined, Error object: {}, Stack: TypeError: o.focus is not a function
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/488.js:1:39821
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:417637)
    at http://127.0.0.1:37840/assets/v0.91.6/app-dist/desktop.js:2:339930
09:53:46.305 204 PUT /api/notes/VuvzR0VspDw6/attributes with 0 bytes took 0ms

**Comment by eliandoran** [comment]
Hi, @Daniel-RUS .

Firstly, issues for TriliumNext should go into https://github.com/TriliumNext/Notes/issues. This is @zadam 's repo, and is in maintenance mode (and we don't always check it).

---

Just to clarify, the error:

```
Parsing error: The keyword ‘count’ is reserved
```

Is actually just an issue with our linter, it was fixed in v0.92.0-beta. This does not affect the running of scripts in any way, only the lists of errors displayed in a code note.

---

I believe the actual error why your scripts are not running is this one:

```
09:15:00.625 JS Error: Uncaught error: Message: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script', Line: undefined, Column: undefined, Error object: {}, Stack: Error: server error: Load of script note "setupButton.js" (HQKpNp5ei6Gx) failed with: scriptNoteId is mandatory for launchers of type 'script'
```

I think there's something wrong with this script. Can you try to find out the content of this note?

**Comment by Daniel-RUS** [comment]
In general, it is when a new base is created that the problem arises. I created a house project and everything worked there, then I packed everything into an archive. It also worked at work. When I replaced the base with a problematic one, the problem persisted. However, having created a new base using the trilium brought from home, everything worked. 

В целом проблема возникает именно при создании новой базы. Я создал проект дома там всё работал, потом всё запаковал в архив. На работе оно также работало. При замене базы на проблемую, проблема сохранилась. Однако создав новую базу с использованием принесённого из дома трилиума, всё разаботало.

**Comment by eliandoran** [comment]
@Daniel-RUS , if you imported the .zip by drag & drop, then this behaviour is to be expected. When you import notes, safe mode is enabled by default. This will disable any scripts or widgets.

This can be solved by using Right click on the note tree -> Import and unchecking "Safe mode".
