### ISSUE TITLE
How to get from 0.31.2-beta back to latest?

### ISSUE THREAD

**Issue by rothbart837** [zadam/trilium#498]
I was running "latest" and got bit by the same downgrade issue a couple of other people were reporting.  I upgraded my Docker container and then it wouldn't load due to missing columns in the database (or something similar.)  

I see a variety of these type of errors in the logs:  
07:21:48.887 INFO  Error: SQLITE_ERROR: table source_ids has no column named dateCreated
16:19:25.373 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table source_ids has no column named dateCreatedError
23:19:25.879 INFO  Error: SQLITE_ERROR: no such column: note_contents.isProtected

Anyway, if I manually specified the 0.31.2-beta tag instead of latest, it starts up and seems to run fine.  My question though, and I'm fairly new to Docker, is how/when can I get back from this specific 0.31.2-beta version and onto the "latest" tagged version?  Will I simply need to wait until latest as a higher version number than 0.31.2-beta?  

Also, am I correct in that typically this isn't something that should happen?  Not trying to point fingers, but generally running "latest" shouldn't be exposing me to application downgrades like this, right?

**Comment by trioxylon** [comment]
Just export your data as a Tar in Trillium by right-clicking the root and then export. In the stable / latest version, import the tar file.

**Comment by zadam** [comment]
There's couple of things - so far :latest tag used to point to both stable and beta releases. If you previously ran on :latest, then you probably had 0.31.X so I recommend upgrading to 0.31.2. If you really want to downgrade to 0.30.8, then I'd go with the approach outlined by @trioxylon 

Some people suggested that it doesn't make sense to tag the beta releases with :latest which I think it's fair so that's why 0.31.2 wasn't initially tagged with :latest which exacerbated this downgrade problem. I retroactively tagged 0.31.2 as :latest and will keep tagging remaining beta releases of 0.31.X, but 0.32.X-beta won't be tagged as :latest anymore which should fix these issues.

**Comment by rothbart837** [comment]
So I'm specifically running zadam/trilium:0.31.2-beta and thought (based on what you said about) that since 0.31.2 is :latest that I should be able to stop specifying 0.31.2-beta and go back to using :latest but I still get an error doing that.  Going back to 0.31.2-beta allows it to work properly again.  I just verified the version from within the Web UI and it said "0.31.2-beta".  How (or when) can I expect to go from specifying a very specific docker tag to just using the latest "release" version (ie. non-beta)?

**Comment by zadam** [comment]
You can now use `0.31-latest` to upgrade between patch releases of the same minor release. Using `latest` is strongly discouraged.

**Comment by rothbart837** [comment]
That worked for me, thank you very much.

So moving forward, is there a recommended way to easily ensure I always have the latest _stable_ release with a single version tag?  I mean once Trilium has moved on to have stable 0.32-whatever versions I'm assuming 0.31-latest will just stay at whatever the last 0.31-whatever was.

**Comment by zadam** [comment]
Starting with 0.32, beta releases won't be tagged with :latest, only stable ones will.

**Comment by rothbart837** [comment]
Okay, so just wait for 0.32 to have some releases, _then_ it will be safe to use :latest again.  Got it.  Thanks again.  Also, thanks for Trilium.  It's become my go-to notebook for things I want to tuck away but come back to later and I have REALLY enjoyed using it via Docker.
